---
environment: production
chdir: /home/file_server/current
address: 127.0.0.1
user: root
# group: root
port: 8087
pid: /home/file_server/currenttmp/thin.pid
rackup: /home/file_server/currentthin/config.ru
log: /home/file_server/currentlog/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true