---
environment: production
chdir: /home/system/file_server/current
address: 127.0.0.1
user: root
# group: root
port: 8087
pid: /home/system/file_server/current/tmp/thin.pid
rackup: /home/system/file_server/current/thin/config.ru
log: /home/system/file_server/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true